CREATE TABLE `altaykz_orders` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `TITLE` VARCHAR(255) NOT NULL,
        `ROOM_ID` INT(11) NOT NULL,
        `DATE_START` TIMESTAMP NOT NULL,
        `DATE_END` TIMESTAMP NOT NULL,
        `TIME_START` VARCHAR(255) NOT NULL,
        `TIME_END` VARCHAR(255) NOT NULL,
        `FIO` VARCHAR(255) NOT NULL,
        `EMAIL` VARCHAR(255) NOT NULL,
        `PHONE` VARCHAR(255) NOT NULL,
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
    );
    
 